Repository OpenVoxProject/openvox, pull requests merged in 2025-05, with the labels that each got.

#62 Remove require for module_tool/contents_description
  lib/puppet/module_tool.rb
Labels: bug

#65 Setup gem publishing to rubygems and github
  .github/workflows/release.yaml
  .gitignore
Labels: github_actions

#69 fix: formatting issues in various spec files
  spec/unit/application/facts_spec.rb
  spec/unit/file_serving/configuration_spec.rb
  spec/unit/functions/join_spec.rb
  spec/unit/graph/sequential_prioritizer_spec.rb
  spec/unit/info_service_spec.rb
  spec/unit/network/formats_spec.rb
  spec/unit/parser/functions/sprintf_spec.rb
  spec/unit/parser/functions/template_spec.rb
  spec/unit/parser/templatewrapper_spec.rb
  spec/unit/pops/loaders/loaders_spec.rb
  spec/unit/pops/types/string_converter_spec.rb
  spec/unit/provider/package/puppetserver_gem_spec.rb
  spec/unit/task_spec.rb
  spec/unit/util/command_line_spec.rb
  spec/unit/util/json_spec.rb
  spec/unit/util/log_spec.rb
  spec/unit/util/logging_spec.rb
  spec/unit/util_spec.rb
Labels: enhancement, tech-debt

#63 Add 'implementation' fact to agent and server.
  lib/puppet/node/facts.rb
  lib/puppet/node/server_facts.rb
  spec/unit/node/facts_spec.rb
Labels: enhancement

#82 Generate human-readable ChangeLog
  .github/workflows/release.yaml
  Gemfile
  Rakefile
  puppet.gemspec
Labels: skip-changelog

#84 Release 8.19.0
  CHANGELOG.md
  lib/puppet/version.rb
Labels: skip-changelog
