Repository OpenVoxProject/openvox, pull requests merged in 2025-06, with the labels that each got.

#91 Fix invalid gemspec in AIO package
  puppet.gemspec
Labels: bug

#92 Release 8.19.1
  CHANGELOG.md
  lib/puppet/version.rb
  puppet.gemspec
Labels: skip-changelog

#93 Generate human-readable ChangeLog
  Gemfile
  Rakefile
Labels: skip-changelog

#95 Borrow the release workflow from the main branch
  .github/workflows/release.yaml
Labels: skip-changelog

#100 Reflect Ruby 3.4 stack trace changes
  lib/puppet/util.rb
  spec/unit/util/logging_spec.rb
Labels: bug

#98 Add base64 and syslog as gem dependencies for Ruby 3.4
  puppet.gemspec
Labels: bug

#115 Release 7.37.2
  .github/workflows/release.yaml
  CHANGELOG.md
  lib/puppet/version.rb
  puppet.gemspec
Labels: skip-changelog

#117 Release 8.19.2
  CHANGELOG.md
  Rakefile
  lib/puppet/version.rb
  puppet.gemspec
Labels: skip-changelog

#118 Release: Fix path to gem
  .github/workflows/release.yaml
Labels: skip-changelog

#131 CI: Output bundle environment
  .github/workflows/rspec_tests.yaml
Labels: github_actions

#130 rspec-mocks: Pin to < 3.13.3
  Gemfile
  lib/puppet/face/facts.rb
  puppet.gemspec
  spec/unit/application/facts_spec.rb
  spec/unit/provider/package/puppetserver_gem_spec.rb
Labels: skip-changelog

#129 rspec-mocks: Pin to < 3.13.3
  Gemfile
Labels: skip-changelog

#139 Remove `pending` when testing StringConverter with JRuby
  spec/unit/pops/types/string_converter_spec.rb
Labels: skip-changelog

#138 Add prepare_release / release workflows
  .github/workflows/gem_release.yaml
  .github/workflows/prepare_release.yml
  .github/workflows/release.yml
  Rakefile
  tasks/tag.rake
  tasks/vox.rake
Labels: skip-changelog

#145 CI: Fix gem release workflow
  .github/workflows/gem_release.yaml
Labels: github_actions, skip-changelog

#146 Rakefile: use new git repo name
  Rakefile
Labels: skip-changelog
