Repository OpenVoxProject/openvox, pull requests merged in 2025-08, with the labels that each got.

#181 CI: Enable Windows 8.3 filesystem compatibility
  .github/workflows/tests.yaml
Labels: skip-changelog

#165 Respect systemd's RUNTIME_DIRECTORY environment variable
  lib/puppet/util/run_mode.rb
Labels: enhancement

#171 Ensure confdir exists
  lib/puppet/face/config.rb
  spec/unit/face/config_spec.rb
Labels: bug

#172 treat windows service accounts as case insensitive
  lib/puppet/provider/service/windows.rb
Labels: bug
